before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  script:
    - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

push:
  script:
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
